### ISSUE TITLE
0.8.1 not in egg repositories

### ISSUE THREAD

**Issue by wasamasa** [ursetto/sql-de-lite#10]
Despite the 0.8.1 tag being over two weeks old now, it still hasn't made it into the egg repositories, most likely because the release-info files haven't been updated. I'm not sure whether it's fine to update/amend all mentions of 0.8.0 accordingly or whether a new release is required where all version numbers are bumped before tagging.

**Comment by ursetto** [comment]
Let me check. I have a .bumpversion.cfg that will automatically update every necessary file and bump the tag. I'm not sure how the tag got added without bumping version.

**Comment by ursetto** [comment]
Turns out git pushed the 0.8.1 tag, but it was 1 commit ahead of master. I've pushed master now and it should have fixed the problem.

Please confirm and I'll close your issue and pull.

**Comment by wasamasa** [comment]
Ah, that explains the Git weirdness I've had when creating the pull request. Vandusen announced 0.8.1 now and the package appears on both egg mirrors.

**Comment by ursetto** [comment]
Awesome.
